### ISSUE TITLE
セミナー申込のテーブル構造を定義する

### ISSUE THREAD

**Issue by YujiMiyashita** [DiveintoCode-corp/DIC_thema_lesson#12]
* ブログモデルを作成する
* テーブル構造はwikiに記載されているのでそれを元にマイグレーションファイルを作成、マイグレーションを行う。

**Comment by timeshiftseiya** [comment]
https://github.com/DiveintoCode-corp/DIC_thema_lesson/wiki/%E3%82%BB%E3%83%9F%E3%83%8A%E3%83%BC%E7%94%B3%E8%BE%BC%E6%A9%9F%E8%83%BD
