### ISSUE TITLE
ヘッダーとフッターを作成する

### ISSUE THREAD

**Issue by YujiMiyashita** [DiveintoCode-corp/DIC_thema_lesson#3]
* application.html.erbに直接書くのではなく、ヘッダーとフッターをパーシャル化する
* 配置場所はapp/views/layoutsの中
* フッターには以下を記述する

<div class='container'>
    <p>Copyright &copy; 2016 DIVE INTO CODE All Rights Reserved.</p>
</div>

**Comment by timeshiftseiya** [comment]
#1

**Comment by YujiMiyashita** [comment]
池田さんお願いします！
